"""PM Workbench session artifacts.

This is an MVP implementation to support experiments:
- Generate a workbench session markdown file under specs/workbench/sessions/
- Choose a Next Move based on current unknowns
- Prefer using adopted tools (from Toolsmith) when a move requires tooling

This is intentionally simple and heuristic-driven.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import frontmatter

from cub.core.toolsmith.adoption import AdoptionStore


@dataclass(frozen=True)
class WorkbenchSessionPaths:
    session_path: Path


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _default_session_id(now: datetime | None = None) -> str:
    now = now or _utc_now()
    return now.strftime("wb-%Y-%m-%d-%H%M%S")


def _read_spec_frontmatter(path: Path) -> dict[str, Any]:
    post = frontmatter.load(path)
    if isinstance(post.metadata, dict):
        return post.metadata
    return {}


def _pick_adopted_tool(preferred_ids: list[str]) -> str | None:
    adopted = AdoptionStore.default().list_all()
    adopted_ids = {a.tool_id for a in adopted}
    for tid in preferred_ids:
        if tid in adopted_ids:
            return tid
    return None


def create_pm_workbench_session(
    *,
    spec_path: Path,
    out_dir: Path,
    session_id: str | None = None,
) -> WorkbenchSessionPaths:
    """Create a new PM Workbench session file.

    For now this targets the spec structure used in specs/researching/pm-workbench.md.

    Args:
        spec_path: Path to the PM workbench spec
        out_dir: Directory to write sessions into
        session_id: Optional explicit session id

    Returns:
        WorkbenchSessionPaths
    """
    now = _utc_now()
    sid = session_id or _default_session_id(now)

    meta = _read_spec_frontmatter(spec_path)
    readiness = meta.get("readiness") or {}
    questions = (readiness.get("questions") or []) if isinstance(readiness, dict) else []

    # Unknowns: seed from readiness questions (best available structured input).
    unknowns = []
    for idx, q in enumerate(questions[:8], start=1):
        unknowns.append(
            {
                "id": f"unk-{idx:03d}",
                "type": "clarity" if "scope" in str(q).lower() else "decision",
                "title": str(q),
                "score": 0.6,
                "rationale": "Seeded from spec readiness questions",
            }
        )

    # Choose Next Move:
    # If we have any unknowns at all, a cheap and high-leverage move is research / competitive scan.
    research_tool = _pick_adopted_tool(["mcp-official:brave-search"])

    next_move: dict[str, Any] = {
        "kind": "research",
        "target_unknown_id": unknowns[0]["id"] if unknowns else None,
        "timebox_minutes": 10,
        "tool_id": research_tool,
        "prompt": [
            "Search prior art frameworks for 'unknowns ledger' + 'next move' PM tooling",
            "Collect 5-10 sources, extract 3 reusable primitives, write a short note",
        ],
        "queries": [
            "product discovery framework next step uncertainty reduction",
            "Shape Up appetite shaping boundaries",
            "Opportunity Solution Tree product discovery",
            "continuous discovery habits weekly touchpoints",
        ],
        "artifact_plan": {
            "path": "specs/investigations/research/pm-workbench-competitive-notes.md",
            "format": "markdown",
        },
    }

    out_dir.mkdir(parents=True, exist_ok=True)
    session_path = out_dir / f"{sid}.md"

    fm = {
        "id": sid,
        "created": now.isoformat(),
        "status": "active",
        "inputs": [
            {"kind": "file", "path": str(spec_path)},
        ],
        "unknowns": unknowns,
        "next_move": next_move,
        "links": [],
    }

    body = (
        "# PM Workbench Session\n\n"
        "This session was generated by Cub (MVP).\n\n"
        "## Notes\n\n"
        "- Unknowns are seeded from the spec frontmatter readiness.questions.\n"
        "- Next Move prefers an adopted tool when available.\n"
    )

    post = frontmatter.Post(body, **fm)
    session_path.write_text(frontmatter.dumps(post), encoding="utf-8")

    return WorkbenchSessionPaths(session_path=session_path)
